[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aevum"
version = "2.2.1"
description = "Media Library Scanner"
requires-python = ">=3.8"

[project.scripts]
aevum = "aevum_pkg._cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["aevum_pkg*"]
